title: Python Portfolio - Exploratory Data Analysis of Job Postings 
logo: assets/images/Findings Q5.png
show_downloads: True
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
